#!/bin/bash
# A very basic start-stop script, see also:
# http://dev.catalystframework.org/wiki/gettingstarted/howtos/deploy/lighttpd_fastcgi

PID_FILE="/home/rob/develop/App-ForExample/Eg/eg-fastcgi-host-port.pid"

case "$1" in
    start)
        echo "Starting"
        /home/rob/develop/App-ForExample/Eg/script/eg_fastcgi.pl -l 127.0.0.1:45450 -n 5 -p $PID_FILE
    ;;
    stop)
        if [ -s "$PID_FILE" ]; then
            echo "Stopping"
            PID=`cat "$PID_FILE"`
            kill -TERM $PID
        fi
    ;;
    restart)
        $0 stop
        sleep 2
        $0 start
    ;;
    *)
        echo "Don't understand \"$1\ ($*)"
        echo "Usage: $0 { start | stop | restart }"
        exit -1
    ;;
esac
