#!/usr/bin/perl

use strict;
use warnings;

use File::Find;
use Path::Class;

print <<_END_;
package App::ForExample::CatalogSource;
1;
__DATA__
_END_

find( { no_chdir => 1, wanted => sub {
    my $path = $_;
    return ($File::Find::prune = 1) if
        $path =~ m/\.sw.$/ or
        0
    ;
    return unless -f $path;
    (my $asset = $path) =~ s/^assets\///;
    my $file = file $path;
    print "$asset\n";
    print scalar $file->slurp;
    print "__ASSET__\n";
} }, qw/assets/ );
