#!/bin/bash

BUILD="./script/build-eg"

HOST_PORT_SOCKET="127.0.0.1:45450"

$BUILD catalyst/fastcgi apache2 dynamic > Eg/apache2/fastcgi-dynamic
$BUILD catalyst/fastcgi --no-bundle apache2 standalone > Eg/apache2/fastcgi-standalone
$BUILD catalyst/fastcgi --no-bundle --fastcgi-socket $HOST_PORT_SOCKET apache2 standalone > Eg/apache2/fastcgi-standalone-host-port
$BUILD catalyst/fastcgi apache2 static > Eg/apache2/fastcgi-static
$BUILD catalyst/mod_perl > Eg/apache2/mod_perl
$BUILD catalyst/fastcgi --no-bundle nginx > Eg/nginx/standalone
$BUILD catalyst/fastcgi --no-bundle --fastcgi-socket $HOST_PORT_SOCKET nginx > Eg/nginx/standalone-host-port
$BUILD catalyst/fastcgi --no-bundle lighttpd standalone > Eg/lighttpd/standalone
$BUILD catalyst/fastcgi --no-bundle --fastcgi-socket $HOST_PORT_SOCKET lighttpd standalone > Eg/lighttpd/standalone-host-port
$BUILD catalyst/fastcgi --fastcgi-socket /tmp/lighttpd-eg.socket lighttpd static > Eg/lighttpd/static
$BUILD catalyst/fastcgi/start-stop --fastcgi-pid-file "eg-fastcgi.pid" > Eg/fastcgi-start-stop
$BUILD catalyst/fastcgi/start-stop --fastcgi-pid-file "eg-fastcgi-host-port.pid" --fastcgi-socket $HOST_PORT_SOCKET > Eg/fastcgi-start-stop-host-port
$BUILD catalyst/fastcgi/monit --fastcgi-pid-file "eg-fastcgi.pid"
$BUILD catalyst/fastcgi/monit --fastcgi-pid-file "eg-fastcgi-host-port.pid"

#Eg
#|-- Changes
#|-- Makefile.PL
#|-- README
#|-- apache2
#|   |-- fastcgi-dynamic
#|   |-- fastcgi-standalone
#|   |-- fastcgi-static
#|   `-- mod_perl
#|-- eg.conf
#|-- fastcgi
#|-- lib
#|   |-- Eg
#|   |   |-- Controller
#|   |   |   `-- Root.pm
#|   |   |-- Model
#|   |   `-- View
#|   `-- Eg.pm
#|-- lighttpd
#|   |-- standalone
#|   `-- static
#|-- nginx
#|   `-- standalone
#|-- root
#|-- script
#|   |-- eg_cgi.pl
#|   |-- eg_create.pl
#|   |-- eg_fastcgi.pl
#|   |-- eg_server.pl
#|   `-- eg_test.pl
#`-- t
#    `-- 00-load.t

#11 directories, 20 files
