#!/bin/bash

BUILD="./script/build-eg"
FOR_EXAMPLE="./script/for-example"

HOST_PORT_SOCKET="127.0.0.1:45450"

#$BUILD catalyst/fastcgi apache2 dynamic > Eg/apache2/fastcgi-dynamic
#$BUILD catalyst/fastcgi --bare apache2 standalone > Eg/apache2/fastcgi-standalone
#$BUILD catalyst/fastcgi --bare --fastcgi-socket $HOST_PORT_SOCKET apache2 standalone > Eg/apache2/fastcgi-standalone-host-port
##$BUILD catalyst/fastcgi apache2 static > Eg/apache2/fastcgi-static
#$BUILD catalyst/mod_perl > Eg/apache2/mod_perl
#$BUILD catalyst/fastcgi --bare nginx > Eg/nginx/standalone
#$BUILD catalyst/fastcgi --bare --fastcgi-socket $HOST_PORT_SOCKET nginx > Eg/nginx/standalone-host-port
#$BUILD catalyst/fastcgi --bare lighttpd standalone > Eg/lighttpd/standalone
#$BUILD catalyst/fastcgi --bare --fastcgi-socket $HOST_PORT_SOCKET lighttpd standalone > Eg/lighttpd/standalone-host-port
#$BUILD catalyst/fastcgi --fastcgi-socket /tmp/lighttpd-eg.socket lighttpd static > Eg/lighttpd/static
#$BUILD catalyst/fastcgi/start-stop --fastcgi-pid-file "eg-fastcgi.pid" > Eg/fastcgi-start-stop
#$BUILD catalyst/fastcgi/start-stop --fastcgi-pid-file "eg-fastcgi-host-port.pid" --fastcgi-socket $HOST_PORT_SOCKET > Eg/fastcgi-start-stop-host-port
#$BUILD catalyst/fastcgi/monit --fastcgi-pid-file "eg-fastcgi.pid"
#$BUILD catalyst/fastcgi/monit --fastcgi-pid-file "eg-fastcgi-host-port.pid"

$BUILD catalyst/fastcgi apache2 dynamic > t/assets/apache2/fastcgi-dynamic
$BUILD catalyst/fastcgi --bare apache2 standalone > t/assets/apache2/fastcgi-standalone
$BUILD catalyst/fastcgi --bare --fastcgi-socket $HOST_PORT_SOCKET apache2 standalone > t/assets/apache2/fastcgi-standalone-host-port
$BUILD catalyst/fastcgi apache2 static > t/assets/apache2/fastcgi-static
$BUILD catalyst/mod_perl > t/assets/apache2/mod_perl
$BUILD catalyst/fastcgi --bare nginx > t/assets/nginx/standalone
$BUILD catalyst/fastcgi --bare --fastcgi-socket $HOST_PORT_SOCKET nginx > t/assets/nginx/standalone-host-port
$BUILD catalyst/fastcgi --bare lighttpd standalone > t/assets/lighttpd/standalone
$BUILD catalyst/fastcgi --bare --fastcgi-socket $HOST_PORT_SOCKET lighttpd standalone > t/assets/lighttpd/standalone-host-port
$BUILD catalyst/fastcgi --fastcgi-socket /tmp/lighttpd-eg.socket lighttpd static > t/assets/lighttpd/static
$BUILD catalyst/fastcgi/start-stop --fastcgi-pid-file "eg-fastcgi.pid" > t/assets/fastcgi-start-stop
$BUILD catalyst/fastcgi/start-stop --fastcgi-pid-file "eg-fastcgi-host-port.pid" --fastcgi-socket $HOST_PORT_SOCKET > t/assets/fastcgi-start-stop-host-port
$BUILD catalyst/fastcgi/monit --fastcgi-pid-file "eg-fastcgi.pid" > t/assets/fastcgi-monit
$BUILD catalyst/fastcgi/monit --fastcgi-pid-file "eg-fastcgi-host-port.pid" > t/assets/fastcgi-monit-host-port
$FOR_EXAMPLE monit --home /home/rob/monit > t/assets/monit

cp t/assets/fastcgi-start-stop* Eg/
cat t/assets/fastcgi-monit*

#Eg
#|-- Changes
#|-- Makefile.PL
#|-- README
#|-- apache2
#|   |-- fastcgi-dynamic
#|   |-- fastcgi-standalone
#|   |-- fastcgi-static
#|   `-- mod_perl
#|-- eg.conf
#|-- fastcgi
#|-- lib
#|   |-- Eg
#|   |   |-- Controller
#|   |   |   `-- Root.pm
#|   |   |-- Model
#|   |   `-- View
#|   `-- Eg.pm
#|-- lighttpd
#|   |-- standalone
#|   `-- static
#|-- nginx
#|   `-- standalone
#|-- root
#|-- script
#|   |-- eg_cgi.pl
#|   |-- eg_create.pl
#|   |-- eg_fastcgi.pl
#|   |-- eg_server.pl
#|   `-- eg_test.pl
#`-- t
#    `-- 00-load.t

#11 directories, 20 files
